# Generated by Django 5.2.5 on 2025-08-29 16:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('geometry', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('country_code', models.CharField(max_length=2)),
                ('locode', models.CharField(blank=True, max_length=10)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('timezone', models.CharField(max_length=64)),
            ],
            options={
                'indexes': [models.Index(fields=['locode'], name='locode_idx')],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('country_code', models.CharField(max_length=2)),
                ('locode', models.CharField(blank=True, max_length=10)),
                ('bic_code', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('smdg_code', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('imo', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('mmsi', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('call_sign', models.CharField(blank=True, max_length=50)),
                ('flag', models.CharField(blank=True, max_length=80)),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_vehicles', to='core.location')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='core.route')),
            ],
        ),
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField()),
                ('route_type', models.CharField(max_length=16)),
                ('geometry', models.TextField()),
                ('mode', models.CharField(blank=True, max_length=16)),
                ('eta_start', models.DateTimeField(blank=True, null=True)),
                ('eta_end', models.DateTimeField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='core.route')),
            ],
            options={
                'ordering': ['route', 'seq'],
                'indexes': [models.Index(fields=['route', 'seq'], name='route_seq_idx')],
            },
        ),
        migrations.CreateModel(
            name='PortCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voyage', models.CharField(max_length=40)),
                ('event', models.CharField(max_length=16)),
                ('label', models.CharField(max_length=8)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('actual_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('source_ref', models.CharField(blank=True, max_length=120)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='port_calls', to='core.facility')),
                ('port_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_calls', to='core.location')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_calls', to='core.vehicle')),
            ],
            options={
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['vehicle', 'scheduled_at'], name='portcall_sched_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheme', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=120)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='core.vehicle')),
            ],
            options={
                'unique_together': {('scheme', 'value')},
            },
        ),
        migrations.CreateModel(
            name='VehiclePosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('source', models.CharField(blank=True, max_length=60)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_positions', to='core.location')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.vehicle')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['vehicle', 'recorded_at'], name='vehpos_time_idx')],
            },
        ),
    ]
