# Generated by Django 5.2.5 on 2025-08-31 16:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('layout_config', models.TextField()),
                ('required_permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dashboards', to='rbac.permission')),
            ],
        ),
    ]
