# Generated by Django 5.2.5 on 2025-09-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment_id', models.UUIDField(db_index=True)),
                ('current_route_id', models.UUIDField(blank=True, null=True)),
                ('proposed_route_id', models.UUIDField(blank=True, null=True)),
                ('input_snapshot', models.JSONField()),
                ('output_decision', models.JSONField()),
                ('approved', models.BooleanField(null=True)),
            ],
        ),
    ]
