# Generated by Django 5.2.5 on 2025-09-17 05:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_reroute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shipment_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=20)),
                ('current_route_id', models.UUIDField(blank=True, null=True)),
                ('current_eta_minutes', models.IntegerField(blank=True, null=True)),
                ('current_toll_cost_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_path', models.JSONField(blank=True, null=True)),
                ('current_p_delay', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('proposed_route_id', models.UUIDField(blank=True, null=True)),
                ('proposed_eta_minutes', models.IntegerField(blank=True, null=True)),
                ('proposed_toll_cost_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proposed_path', models.JSONField(blank=True, null=True)),
                ('proposed_p_delay', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('rationale', models.TextField()),
                ('requires_approval', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied')], default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shipment_id', 'status'], name='agent_rerou_shipmen_d0d048_idx')],
            },
        ),
    ]
