// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9AFlLX8AnTGFGypvo3gaS-ONQE_6Aj7M',
    appId: '1:727485567402:web:ff8c1f48c4b6c6b5035bd3',
    messagingSenderId: '727485567402',
    projectId: 'cargosmart-e2a12',
    authDomain: 'cargosmart-e2a12.firebaseapp.com',
    storageBucket: 'cargosmart-e2a12.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxhcmFjPLMh_X_8TcyqDAiue09YMyp7I0',
    appId: '1:727485567402:android:a3fa21b22253992f035bd3',
    messagingSenderId: '727485567402',
    projectId: 'cargosmart-e2a12',
    storageBucket: 'cargosmart-e2a12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVFBXZ8T38mUM4GtONq_NjGJ6TLUZtpDc',
    appId: '1:727485567402:ios:313dc4c32307e708035bd3',
    messagingSenderId: '727485567402',
    projectId: 'cargosmart-e2a12',
    storageBucket: 'cargosmart-e2a12.firebasestorage.app',
    iosBundleId: 'com.example.cargoSmartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVFBXZ8T38mUM4GtONq_NjGJ6TLUZtpDc',
    appId: '1:727485567402:ios:313dc4c32307e708035bd3',
    messagingSenderId: '727485567402',
    projectId: 'cargosmart-e2a12',
    storageBucket: 'cargosmart-e2a12.firebasestorage.app',
    iosBundleId: 'com.example.cargoSmartApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9AFlLX8AnTGFGypvo3gaS-ONQE_6Aj7M',
    appId: '1:727485567402:web:70ad1356d4619aec035bd3',
    messagingSenderId: '727485567402',
    projectId: 'cargosmart-e2a12',
    authDomain: 'cargosmart-e2a12.firebaseapp.com',
    storageBucket: 'cargosmart-e2a12.firebasestorage.app',
  );
}
