# Generated by Django 5.2.5 on 2025-08-29 16:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('layout_config', models.JSONField(default=dict)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='rbac.role')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionOpObj',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('objectmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_operations', to='rbac.objectmodel')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_objects', to='rbac.operation')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op_objects', to='rbac.permission')),
            ],
            options={
                'db_table': 'permission_ops_objs',
                'indexes': [models.Index(fields=['permission', 'operation', 'objectmodel'], name='perm_op_obj_idx')],
                'unique_together': {('permission', 'operation', 'objectmodel')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='rbac.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='rbac.role')),
            ],
            options={
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
