# Generated by Django 5.2.5 on 2025-09-07 09:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('geometry', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField()),
                ('route_type', models.CharField(max_length=50)),
                ('geometry', models.TextField()),
                ('mode', models.CharField(max_length=50)),
                ('eta_start', models.DateTimeField(blank=True, null=True)),
                ('eta_end', models.DateTimeField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='routes.route')),
            ],
            options={
                'ordering': ['seq'],
                'constraints': [models.UniqueConstraint(fields=('route', 'seq'), name='uniq_route_seq')],
            },
        ),
    ]
