# Generated by Django 5.2.5 on 2025-09-05 06:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('iso_code', models.CharField(max_length=10)),
                ('size_type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContainerEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voyage', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(max_length=50)),
                ('event_code', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('route_type', models.CharField(max_length=50)),
                ('transport_type', models.CharField(blank=True, max_length=50, null=True)),
                ('happened_at', models.DateTimeField()),
                ('is_actual', models.BooleanField(default=False)),
                ('is_additional', models.BooleanField(default=False)),
                ('source', models.CharField(max_length=50)),
                ('ingested_at', models.DateTimeField()),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='containers.container')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_events', to='geo.facility')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_events', to='geo.location')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_events', to='vehicles.vehicle')),
            ],
            options={
                'indexes': [models.Index(fields=['container', 'happened_at'], name='idx_container_event_timeline')],
                'constraints': [models.UniqueConstraint(fields=('container', 'event_code', 'happened_at', 'location', 'source'), name='uniq_container_event_fingerprint')],
            },
        ),
    ]
