# Generated by Django 5.2.5 on 2025-09-05 06:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('imo', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('mmsi', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('call_sign', models.CharField(blank=True, max_length=50)),
                ('flag', models.CharField(blank=True, max_length=50)),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_here', to='geo.location')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='routes.route')),
            ],
        ),
        migrations.CreateModel(
            name='PortCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voyage', models.CharField(blank=True, max_length=50)),
                ('event', models.CharField(max_length=50)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('actual_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('source_ref', models.CharField(blank=True, max_length=100)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='port_calls', to='geo.facility')),
                ('port_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='port_calls', to='geo.location')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_calls', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheme', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='vehicles.vehicle')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scheme', 'value'), name='uniq_vehicle_identifier')],
            },
        ),
        migrations.CreateModel(
            name='VehiclePosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('source', models.CharField(max_length=50)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_positions', to='geo.location')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='vehicles.vehicle')),
            ],
            options={
                'indexes': [models.Index(fields=['vehicle', 'recorded_at'], name='idx_vehicle_recorded_at')],
            },
        ),
    ]
