# Generated by GPT assistant to align DB schema with models (add driver FK)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('accounts', '0001_initial'),
		('vehicles', '0001_initial'),
	]

	operations = [
		migrations.AddField(
			model_name='vehicle',
			name='driver',
			field=models.ForeignKey(
				on_delete=django.db.models.deletion.SET_NULL,
				null=True,
				blank=True,
				related_name='assigned_vehicles',
				to='accounts.user'
			),
		),
	]


