# Generated by Django 5.2.5 on 2025-09-14 18:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('country_code', models.CharField(default='IN', max_length=3)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
            ],
        ),
    ]
