# Generated by Django 5.2.5 on 2025-09-05 06:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=3)),
                ('locode', models.CharField(blank=True, max_length=10)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('timezone', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('country_code', models.CharField(max_length=3)),
                ('locode', models.CharField(blank=True, max_length=10)),
                ('bic_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('smdg_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='geo.location')),
            ],
        ),
    ]
