# Generated by Django 5.2.5 on 2025-09-07 09:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('containers', '0001_initial'),
        ('geo', '0001_initial'),
        ('routes', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref_no', models.CharField(max_length=64, unique=True)),
                ('shipment_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('carrier_code', models.CharField(blank=True, max_length=20)),
                ('carrier_name', models.CharField(blank=True, max_length=100)),
                ('api_updated_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField()),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_shipments', to='geo.location')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_shipments', to='geo.location')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shipments', to=settings.AUTH_USER_MODEL)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_shipments', to='geo.location')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='routes.route')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('actual', models.BooleanField(default=False)),
                ('predictive_eta', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_milestones', to='geo.location')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='shipments.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('ROUTE_CHANGE', 'Route Change'), ('STATUS_CHANGE', 'Status Change'), ('DRIVER_CHANGE', 'Driver Change'), ('MILESTONE_REACHED', 'Milestone Reached'), ('DELAY', 'Delay')], max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shipments.shipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentVehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voyage', models.CharField(blank=True, max_length=50)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_vehicles', to='shipments.shipment')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_vehicles', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentContainer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('loaded_at', models.DateTimeField(blank=True, null=True)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_containers', to='containers.container')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_containers', to='shipments.shipment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('shipment', 'container'), name='uniq_shipment_container')],
            },
        ),
    ]
