# Generated by Django 5.2.5 on 2025-08-29 16:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('iso_code', models.CharField(max_length=10)),
                ('size_type', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref_no', models.CharField(max_length=80, unique=True)),
                ('shipment_type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=30)),
                ('carrier_code', models.CharField(max_length=10)),
                ('carrier_name', models.CharField(max_length=120)),
                ('api_updated_at', models.DateTimeField()),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_current_loc_set', to='core.location')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_destination_set', to='core.location')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_origin_set', to='core.location')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='core.route')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('actual', models.BooleanField(default=False)),
                ('predictive_eta', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_milestones', to='core.location')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='shipments.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleLeg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voyage', models.CharField(max_length=40)),
                ('role', models.CharField(blank=True, max_length=20)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_legs', to='shipments.shipment')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_legs', to='core.vehicle')),
            ],
            options={
                'db_table': 'shipment_vehicles',
            },
        ),
        migrations.CreateModel(
            name='ContainerEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voyage', models.CharField(blank=True, max_length=40, null=True)),
                ('description', models.CharField(max_length=200)),
                ('event_type', models.CharField(max_length=20)),
                ('event_code', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('route_type', models.CharField(max_length=10)),
                ('transport_type', models.CharField(blank=True, max_length=16, null=True)),
                ('happened_at', models.DateTimeField()),
                ('is_actual', models.BooleanField(default=False)),
                ('is_additional', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=60)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shipments.container')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_events', to='core.facility')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_events', to='core.location')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_events', to='core.vehicle')),
            ],
            options={
                'ordering': ['-happened_at'],
                'indexes': [models.Index(fields=['container', 'happened_at'], name='ce_container_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('container', 'event_code', 'happened_at', 'location'), name='uniq_container_event')],
            },
        ),
        migrations.CreateModel(
            name='ShipmentContainer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('loaded_at', models.DateTimeField(blank=True, null=True)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_links', to='shipments.container')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_containers', to='shipments.shipment')),
            ],
            options={
                'unique_together': {('shipment', 'container')},
            },
        ),
    ]
